### PR TITLE
Test

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by hoffmang9** [comment]
Intel Core i9-10900K - master at 2020-12-17:
```
Time: 2293 ms; n_slow: 74; speed: 174.4K ips
a = 0x6ce27bdb0240cadd4f5ba8eda519bfbe0ffd5ad3004ff27b9d6f65c62815265730bce32258434615674124e204f3c3429e6c214fd171846f5c0acf27c754ac42
b = -0x2040323dc47947c6161535b2e1366a274671d9bd1f9cb7644cb0da6b237a886a8414c9d9fa33f3fd9d9072b34561bc51e93ec1fbb341f6a18de5dd5c63fa421f
c = 0x78869cb37a6a7d392b19000ce9dc30358093871a2753ea79c0cabe40e283d1a2f60234c2f2f8777fde662a87f55a4cb7fea3489750e83c9cefff52fc594b19ab
```

this PR:
```
Time: 2138 ms; n_slow: 74; speed: 187.0K ips
a = 0x6ce27bdb0240cadd4f5ba8eda519bfbe0ffd5ad3004ff27b9d6f65c62815265730bce32258434615674124e204f3c3429e6c214fd171846f5c0acf27c754ac42
b = -0x2040323dc47947c6161535b2e1366a274671d9bd1f9cb7644cb0da6b237a886a8414c9d9fa33f3fd9d9072b34561bc51e93ec1fbb341f6a18de5dd5c63fa421f
c = 0x78869cb37a6a7d392b19000ce9dc30358093871a2753ea79c0cabe40e283d1a2f60234c2f2f8777fde662a87f55a4cb7fea3489750e83c9cefff52fc594b19ab
```

Example "slowest" runs as there is a lot of variance on each run on this machine with a bit of load on (timelord running in the background.) It's safe to say it does not look slower but we should probably test on a quiet machine too - sumo or beast.

**Comment by arvidn** [comment]
I'm pretty sure the slowdown came from attempting to lazily initialize the GMP integers (which I just pulled out of this PR).

I think there may be some more opportunities for speeding this up too. At least there are some inefficient functions, but maybe they are only used very infrequently.

**Comment by arvidn** [comment]
@hoffmang9 I'm thinking I'll cherry-pick and squash your PR to run the tests on top of the "fix GMP allocation" patch. I imagine that would be sufficient to make the tests pass. If so, I can then rebase all the other fixes in top if master, and they would still have the tests pass.

There's a risk, I suppose, that more than one of these fixes contribute to making the tests pass. In that case, maybe we can consider landing this PR, which is all of them put together (for me to test on the CI)

**Comment by hoffmang9** [comment]
I lean to "let's just land this PR" though I'm about to run some more performance testing on a quiet beast.chia.net (Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz). Back with results shortly. Then we should just merge this and kill off the other branches and PRs. I'll tag it and add it to blockchian/dev

**Comment by hoffmang9** [comment]
master on beast for 9,000,000 - two runs:
```
./vdf_bench square_asm 9000000
Time: 60587 ms; n_slow: 1979; speed: 148.5K ips
a = 0x31120b066b404dc587551d44ef850167ae112463d577509f4150a5c6056b658703c3b984eb0bb9c85c709fd93b24afee3362237dec15caa5e37cf78ae397d4f2
b = -0x15d24723e3bc05095397c1ed4a4e96113be7e12aa9af48d5afed6c5bb2d5ba17d18a0e8eaa9cd24732d712f66f792622ab2b9c4fc07985c05057ad3cd2ef8229
c = 0x108912cdfca561114407f8d95901a78efe8897c49f26c4715709753c7250c4d949a31ded0893fe4d6ea27f0ea2763ef4ac0a35ecc755e7c7f2bd2a60ffe4b304d
(venv) hoffmang@beast:~/chiavdf/src$ ./vdf_bench square_asm 9000000
Time: 61056 ms; n_slow: 1979; speed: 147.4K ips
a = 0x31120b066b404dc587551d44ef850167ae112463d577509f4150a5c6056b658703c3b984eb0bb9c85c709fd93b24afee3362237dec15caa5e37cf78ae397d4f2
b = -0x15d24723e3bc05095397c1ed4a4e96113be7e12aa9af48d5afed6c5bb2d5ba17d18a0e8eaa9cd24732d712f66f792622ab2b9c4fc07985c05057ad3cd2ef8229
c = 0x108912cdfca561114407f8d95901a78efe8897c49f26c4715709753c7250c4d949a31ded0893fe4d6ea27f0ea2763ef4ac0a35ecc755e7c7f2bd2a60ffe4b304d
```

This branch/PR on beast - same args:
```
./vdf_bench square_asm 9000000
Time: 62979 ms; n_slow: 1979; speed: 142.9K ips
a = 0x31120b066b404dc587551d44ef850167ae112463d577509f4150a5c6056b658703c3b984eb0bb9c85c709fd93b24afee3362237dec15caa5e37cf78ae397d4f2
b = -0x15d24723e3bc05095397c1ed4a4e96113be7e12aa9af48d5afed6c5bb2d5ba17d18a0e8eaa9cd24732d712f66f792622ab2b9c4fc07985c05057ad3cd2ef8229
c = 0x108912cdfca561114407f8d95901a78efe8897c49f26c4715709753c7250c4d949a31ded0893fe4d6ea27f0ea2763ef4ac0a35ecc755e7c7f2bd2a60ffe4b304d
(venv) hoffmang@beast:~/chiavdf/src$ ./vdf_bench square_asm 9000000
Time: 62047 ms; n_slow: 1979; speed: 145.0K ips
a = 0x31120b066b404dc587551d44ef850167ae112463d577509f4150a5c6056b658703c3b984eb0bb9c85c709fd93b24afee3362237dec15caa5e37cf78ae397d4f2
b = -0x15d24723e3bc05095397c1ed4a4e96113be7e12aa9af48d5afed6c5bb2d5ba17d18a0e8eaa9cd24732d712f66f792622ab2b9c4fc07985c05057ad3cd2ef8229
c = 0x108912cdfca561114407f8d95901a78efe8897c49f26c4715709753c7250c4d949a31ded0893fe4d6ea27f0ea2763ef4ac0a35ecc755e7c7f2bd2a60ffe4b304d
```
That's not good news.

**Comment by hoffmang9** [comment]
To be sure, I ran some more runs for master and it's more variable than it looks so the above test is inconclusive.

**Comment by arvidn** [comment]
I think it's far fetched that `std::atomic<>` would slow things down. And even if it did, it will produce the correct result rather than an undefined result. However, `master` already has a few fixes with using atomic operations where they are needed, so to be sure, it would make sense to test a few commits back.

**Comment by hoffmang9** [comment]
I did a 2.5 minute compare of test to https://github.com/Chia-Network/chiavdf/commit/1f70ea57071f8b8fb831f58d82686ebb3108f6b4 and it's a wash speed wise.

Which branch should we merge and which should be deleted?

**Comment by arvidn** [comment]
I was thinking that this PR would be deleted. This is where I brought all the PRs together, to ensure they all pass the tests on CI. I think https://github.com/Chia-Network/chiavdf/pull/47 should be the first one to land (it includes your patch to the CI workflow files to run the tests)

**Comment by hoffmang9** [comment]
closing

**Pull request closed without merging**
