### PR TITLE
Leak hunt

### PR DESCRIPTION
**Pull request by arvidn**
some attempts at fixing the memory leak

### CODE REVIEW

**Review by hoffmang9 — APPROVED** [review]
May the hunt begin.

**Comment by arvidn** [comment]
@hoffmang9 I rebased this on top of master now. It passed with all the sanitizers. I suspect this will at least fix the python module, which I understand is what farmers use.

**Comment by hoffmang9** [comment]
Once CI completes, I'll merge it and tag a beta into the dev-vdf-test branch on blockchain

**Comment by hoffmang9** [comment]
I'm running 0.13.1b1 - which is the sanitize branch - on one of the farmers I saw leaks on and it's not leaking there - FYI.

**Pull request merged**
